//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAL.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessToUser
    {
        public int accessID { get; set; }
        public int urlID { get; set; }
        public int UserID { get; set; }
        public bool hasAccess { get; set; }
    
        public virtual Url Url { get; set; }
        public virtual User User { get; set; }
    }
}
