//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAL.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtWorkUpload
    {
        public ArtWorkUpload()
        {
            this.Orders = new HashSet<Order>();
            this.Breakdowns = new HashSet<Breakdown>();
            this.Indents = new HashSet<Indent>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public string refNumber { get; set; }
        public string label { get; set; }
        public string version { get; set; }
        public string combo { get; set; }
        public string itemDescription { get; set; }
        public string brand { get; set; }
        public System.DateTime dateOfSubmission { get; set; }
        public string buyer { get; set; }
        public string comments { get; set; }
        public string status { get; set; }
        public string createdBy { get; set; }
        public string Price { get; set; }
        public string Finishing { get; set; }
        public string isApproved { get; set; }
        public string ApprovedBy { get; set; }
        public string NoteAtFooter { get; set; }
        public System.DateTime DateOfApproval { get; set; }
        public System.DateTime SentForApprovalDate { get; set; }
        public string ReceivedFrom { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Breakdown> Breakdowns { get; set; }
        public virtual ICollection<Indent> Indents { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
