//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAL.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Breakdowns = new HashSet<Breakdown>();
            this.Indents = new HashSet<Indent>();
        }
    
        public string OrderRef { get; set; }
        public string OrderRefNo { get; set; }
        public System.DateTime Date { get; set; }
        public string CustomerName { get; set; }
        public string DeliveryPlace { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string TOCompany { get; set; }
        public string FROMCompany { get; set; }
        public string Attn { get; set; }
        public string AccessoryType { get; set; }
        public long OrderQty { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ReferenceNo { get; set; }
    
        public virtual ArtWorkUpload ArtWorkUpload { get; set; }
        public virtual Size Size { get; set; }
        public virtual ICollection<Breakdown> Breakdowns { get; set; }
        public virtual ICollection<Indent> Indents { get; set; }
    }
}
