//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAL.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public long ID { get; set; }
        public string PO { get; set; }
        public string Style { get; set; }
        public string Ref { get; set; }
        public string OrderQty { get; set; }
        public string Remarks { get; set; }
        public string SN1 { get; set; }
        public Nullable<int> S1 { get; set; }
        public string SN2 { get; set; }
        public Nullable<int> S2 { get; set; }
        public string SN3 { get; set; }
        public Nullable<int> S3 { get; set; }
        public string SN4 { get; set; }
        public Nullable<int> S4 { get; set; }
        public string SN5 { get; set; }
        public Nullable<int> S5 { get; set; }
        public string SN6 { get; set; }
        public Nullable<int> S6 { get; set; }
        public string SN7 { get; set; }
        public Nullable<int> S7 { get; set; }
        public string SN8 { get; set; }
        public Nullable<int> S8 { get; set; }
        public string SN9 { get; set; }
        public Nullable<int> S9 { get; set; }
        public string SN10 { get; set; }
        public Nullable<int> S10 { get; set; }
        public string SN11 { get; set; }
        public Nullable<int> S11 { get; set; }
        public string SN12 { get; set; }
        public Nullable<int> S12 { get; set; }
        public string SN13 { get; set; }
        public Nullable<int> S13 { get; set; }
        public string SN14 { get; set; }
        public Nullable<int> S14 { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Status { get; set; }
        public string ToCompany { get; set; }
        public string FromCompany { get; set; }
        public string Attn { get; set; }
        public string OrderRef { get; set; }
    
        public virtual ArtWorkUpload ArtWorkUpload { get; set; }
    }
}
