//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAL.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long Id { get; set; }
        public System.DateTime WOIssueDate { get; set; }
        public string WO { get; set; }
        public string CustomerName { get; set; }
        public string Buyer { get; set; }
        public string PO { get; set; }
        public string CustomerOrderRef { get; set; }
        public string SL { get; set; }
        public string UALFileName { get; set; }
        public string LabelType { get; set; }
        public string LabelName { get; set; }
        public string Finishing { get; set; }
        public string Version { get; set; }
        public string BuyersRef { get; set; }
        public string OrderQty { get; set; }
        public string Pick { get; set; }
        public string Cutter { get; set; }
        public string Beam { get; set; }
        public string RatePerDzn { get; set; }
        public string TotalAmount { get; set; }
        public string FinishingRate { get; set; }
        public string FinishingTotalAmount { get; set; }
        public string GTotalAmount { get; set; }
        public string AmountReceived { get; set; }
        public string OrderwiseAmountDue { get; set; }
        public string Label { get; set; }
        public Nullable<int> ProductionHours { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string Combo { get; set; }
        public Nullable<bool> IsSizewise { get; set; }
        public Nullable<long> WOS { get; set; }
    
        public virtual WOSize WOSize { get; set; }
    }
}
