//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAL.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public string OrderRef { get; set; }
        public Nullable<long> S { get; set; }
        public Nullable<long> M { get; set; }
        public Nullable<long> L { get; set; }
        public Nullable<long> XL { get; set; }
        public Nullable<long> XXL { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
