//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAL.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Url
    {
        public Url()
        {
            this.AccessToUsers = new HashSet<AccessToUser>();
        }
    
        public int urlID { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<AccessToUser> AccessToUsers { get; set; }
    }
}
