//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAL.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AccessToUsers = new HashSet<AccessToUser>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public long RoleID { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string UserDetails { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<AccessToUser> AccessToUsers { get; set; }
        public virtual Role Role { get; set; }
    }
}
